### PR TITLE
include link for scopeBlacklist

### PR DESCRIPTION
**Pull request by brntbeer**
Not sure if this is the way that you go about adding a proper link as it gets including with js, but at least we can discuss what i think would be helpful.

Currently you can't even highlight and copy the text

### CODE REVIEW

**Comment by benogle** [comment]
We really need to make these auto render. There are a bunch that use links.

**Comment by brntbeer** [comment]
@benogle anything i could look at that would help autoRendering or just keep my fingers crossed and wait?

Happy to just close this out since i've at least planted the seed of this being a thing

**Comment by benogle** [comment]
Closing in favor of https://github.com/atom/settings-view/issues/618 Hopefully we can get to it in the quality initiative.

**Comment by brntbeer** [comment]
thanks @benogle !

**Pull request closed without merging**
