### PR TITLE
use fuzzaldrin-plus by default

### PR DESCRIPTION
**Pull request by jeancroy**
For some reason the request to update ac+ got translated to command palette.
Probably not bad but this still need to be done.

@benogle @nathansobo

### CODE REVIEW

**Comment by jeancroy** [comment]
Ok change in order break two spec. I'll try to see if I can fix them or fz-plus

Provider API
  Provider API v2.0.0
    when the filterSuggestions option is set to true
      it filters suggestions based on the specified replacementPrefix for each suggestion
        Expected [ { text : 'hai' }, { text : 'something' } ] to equal [ { text : 'hai' }, { text : '::cats' }, { text : 'something' } ].

SymbolProvider
  when the autocomplete.symbols changes between scopes
    it uses the config for the scope under the cursor
      Expected 'in-a-string' to be 'invar'. (spec/symbol-provider-spec.coffee:336:35)

**Comment by jeancroy** [comment]
Ok updating to fz-plus 0.3.1 address issue where all query is made of optional character. `::` -> `::cats`
However the test still fail because it prefers `::`->`::cats` to `h`->`hai`. Given there's two character that match I assume new answer is good.

**Comment by jeancroy** [comment]
The other test fail because, given query `in` we prefers `in-a-string` to `invar` on the ground that `in` is a full word in the first candidate and part of a word in the second. Changing - with 0 fix this.

**Comment by jeancroy** [comment]
Note: If you do not want to update this close to release.
Replacing the test `::` -> `::cat`
By `::c` -> `::cat`

will work on old version.

**Comment by jeancroy** [comment]
Ok swtiched to less invasive spec fixing. No need to update anything now.

Only thing that fail is a seemingly unrelated position test
Expected '-161px' to be '-160px'

**Comment by nathansobo** [comment]
Thanks @jeancroy.

**Comment by nathansobo** [comment]
Out with 1.4.0-beta3.

**Comment by axelson** [comment]
There are some cases where it is not performing optimally. For example see: https://github.com/atom/language-ruby/issues/130 where it is preferring `dop` over `do` after typing `do`. 

Also is this still considered experimental even though it is on by default?

**Comment by jeancroy** [comment]
Jason, if you read that thread I beleive it's because of reason outside of
alternate scoring.

Jean Christophe Roy

**Pull request merged**
