### PR TITLE
Update replacementPrefix for suggestions when returned multiple times 

### PR DESCRIPTION
**Pull request by sadikovi**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

This PR adds `isPrefixModified` flag to a suggestion to distinguish between suggestions that originally had prefix set and ones that did not. Original issue was that suggestions get reused without resetting a prefix. This flag checks that we have modified prefix in the past, and so we need to reset to a new one.

For more detailed explanation see https://github.com/atom/autocomplete-plus/issues/975#issuecomment-405086072.

### Alternate Designs

Returning a fresh copy of a suggestion every time `provider.getSuggestions` is called was one of the alternatives. It arguably could be a better approach, but I was trying to avoid extensive copying.

### Benefits

Solves the issue when a suggestion will not be selected correctly. Potentially solves some other related issues.

### Possible Drawbacks

None were observed.

### Applicable Issues

#975.

### CODE REVIEW

**Comment by sadikovi** [comment]
@50Wliu @rsese Could you review this PR, please? Follows the discussion on the issue. Thanks!

**Comment by rsese** [comment]
✨ thanks @sadikovi!  I'm not an engineer so can't do a code review but I think @queerviolet was [happy to take a look 👓](https://github.com/atom/autocomplete-plus/issues/975#issuecomment-406702398)?

**Comment by sadikovi** [comment]
Thanks a lot @queerviolet!

**Comment by queerviolet** [comment]
Thanks for the PR! Looks good, merged.

**Pull request merged**
