### PR TITLE
support german characters for autocompletion

### PR DESCRIPTION
**Pull request by cornz**

### CODE REVIEW

**Comment by benogle** [comment]
Does this actually fix it? Seems like the word regex in the manager would need to be upgraded as well. Also please write a few tests.

**Comment by jeancroy** [comment]
Basically `\w` is [a-zA-Z0-9_]

Maybe we can define word as Not NonWord.

Atom have `editor.nonWordCharacters` wich is ``/\()"':,.;<>~!@#$%^&*|+=[]{}`?-…``
And using this would be consistent with the [cursor methods](
https://github.com/atom/atom/blob/b473d12de993138c50371cf14c2869532fe3c2d2/src/cursor.coffee#L610) that deal with words. (we have to remember to add white spaces to that negated set)

Then the character class `[a-zA-Z_-]` can be understood as the above defined `\w` without `[0-9]` and with addition of `-`. 

Something along those line might be closer to a proper Unicode support. Adding accent one per one, while it may works for a specific language is a tedious route to support all of them.

**Comment by jeancroy** [comment]
`\b` is based on a-z0-9 as well.
Something like `(^|\W)\w+(?=$|\W)` would approximate a word, but because of the lack of look-behind we grab one extra character that need to be managed

**Comment by thomasjo** [comment]
> Something along those line might be closer to a proper Unicode support. Adding accent one per one, while it may works for a specific language is a tedious route to support all of them.

I couldn't agree more. We need to come up with a solution that is not some temporary band-aid solution. Adding unicode letters one by one does not scale.

**Comment by kevinsawicki** [comment]
Just wanted to mention here that autoflow recently got support for Cyrillic characters in a similar style, https://github.com/atom/autoflow/blob/dc9ccef01a293601c25ddd4fc504311f8f23ddd9/lib/autoflow.coffee#L3-L8

It might be interesting to refactor this into a library and/or expose an API for this from core so packages can intelligently 

Looks like there is already a library on NPM that supports English, CJK, and Cyrillic, https://github.com/regexps/word-regex

**Comment by jeancroy** [comment]
XRegExp have proper support for unicode character class.

A positive construction would probably looks like this
https://github.com/slevithan/xregexp/blob/master/src/addons/unicode-categories.js#L63
Well that's letter, number would have to be added and some symbols if so we choose.

That being said negative construction seems easier to implement and possibly faster.

**Comment by nixel2007** [comment]
I've made a PR #667 which add a XRegExp support. Looks like it will close this issue as well.

**Pull request closed without merging**
