### PR TITLE
Add unicode support for \w regexps

### LINKED ISSUE #76: Unicode support
Current implementation seems to break words on unicode characters - so when I write "somēthing" in the editor, it gets tokenised into "som" and "thing" for purposes of autocomplete.

If I follow the code correctly, it's due to JS regex used at [`Provider.wordRegex`](https://github.com/saschagehlich/autocomplete-plus/blob/master/lib/provider.coffee#L6)  not being unicode-enabled.

Possible solutions:
* use a character whitelist [like here](https://github.com/saschagehlich/autocomplete-plus/blob/master/lib/fuzzy-provider.coffee#L61);
* bring in unicode-aware library like [XRegExp](http://xregexp.com/);

Which would you rather see implemented - nasty regex without additional libraries, or cleaner regex plus additional dependency? Or something else entirely?

### PR DESCRIPTION
**Pull request by nixel2007**
Hello.
This is a fix for long-lived bug #76 - autocomplete is broken for non-ascii symbols (cause of `\w`-implementation as `[a-zA-Z0-9_]`)
I took @l-flame idea of adding XRegExp and replacing `\w` to `[\p{L}\d_]` + some tuning for `\b` (it's also based on `\w`).

All 218 specs are "green".

### CODE REVIEW

**Comment by EvilBeaver** [comment]
There are more similar issues in Atom. For example #100 #573 and so on.
It seems this pull request fixes all cases of this bad unicode support.

**Comment by artbear** [comment]
+1

**Comment by benogle** [comment]
This is interesting. One thing that's a little nervewracking is that it's pulling in a new regex library that has a lot of unknowns. We dont know if it's slow, we dont know what other issues are in there, and we dont know about the edges no one has thought about. 

I think the right way forward should be:

1. Make an option, default false, that when enabled, uses this library. When the option is false, it uses built-in regexes as it does today.
1. Do some profiling of this library vs native regexp
1. Write specs for a number of unicode cases that utilize all the changed regexes

**Comment by nixel2007** [comment]
Hi, @benogle 
1. I think that making an option is not a good idea. I see request about this feature since 2014 year. People really waits for this for a long time.
2. If you have some fears about lib, we can extract the /p{L} sequence and us it like this:
```cson
Letters = "0-9A-Za-z\xAA\xB5\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02C1\u02C6-\u02D1\_and_so_on_and_so_on"
...
wordPrefixRegex: RegExp ('^[' + Letters + '\\d_]+[' + Letters + '-\\d_]*$')
```

So, you have no extra dependencies AND have needed behavior.
Nevertheless, XRegExp is widely used lib. [Search result on github](https://github.com/search?q=XRegExp&type=Code&utf8=%E2%9C%93)
3. Specs is always a good idea.

**Comment by 50Wliu** [comment]
> 1. I think that making an option is not a good idea. I see request about this feature since 2014 year. People really waits for this for a long time.

Having an option makes sure that there are no regressions, and people can enable/disable it at will.  This was the same approach done for fuzzy finding (which had even more requests, also since 2014) and other major features such as preview tabs or the Shadow DOM.  After a while if everything is proven stable then the default can be switched to true or even removed (as in the case of preview tabs).

**Comment by nixel2007** [comment]
@50Wliu do you think this option should be editor-wide or could be specified for specific language?

Me and my colleauges tested it for our language package (in both ascii and non-ascii variants). it would be great if we could turn this flag on when packege activate()

**Comment by nixel2007** [comment]
Here some updates for this PR.

1) Removed xRegExp dependensy (see section with profiling).  
2) Rewrited old providers specs with unicode support  
3) Added a new package setting `enableExtendedUnicodeSupport` - "Identifies non-latin alphabet characters as letters". Turned off by default.   
4) Made some profiling for getSuggestions.

enableExtendedUnicodeSupport is **disabled**:
falseenableextendedunicodesupport

enableExtendedUnicodeSupport is **enabled**:
trueenableextendedunicodesupport

old version with XRegExp-lib:
xregexp

Please, review. @benogle @50Wliu 

Maybe you'll want to get xRegExp dep back or hide `letters` variable in some module, to reduce the width of file and code duplication

**Comment by benogle** [comment]
Thanks for this!

**Comment by TimvdLippe** [comment]
Amazing news, thanks for the hard work!

**Pull request merged**
