### PR TITLE
fix #722 check path before passing it to basename

### LINKED ISSUE #722: Uncaught TypeError: Path must be a string. Received undefined
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: "Arch Linux"
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.29.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at AutocompleteManager.module.exports.AutocompleteManager.isCurrentFileBlackListed (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:623:23)
    at AutocompleteManager.isCurrentFileBlackListed (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:266:16)
    at /usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:16.8.0 core:copy (atom-text-editor.editor.is-focused.mini)
     -0:08.4.0 core:paste (atom-text-editor.editor.is-focused.mini)
 24x -0:05.7.0 core:move-up (atom-text-editor.editor.is-focused.mini)
     -0:02.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused.mini)
     -0:02.6.0 editor:newline (atom-text-editor.editor.is-focused.mini)
     -0:02.5.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused.mini)
     -0:02.5.0 editor:newline (atom-text-editor.editor.is-focused.mini)
     -0:02.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "linter-cpplint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-moose, v0.20.0
build, v0.63.0
build-cmake, v0.4.0
build-make, v0.9.0
column-select, v0.2.0
gcc-make-run, v0.2.7
language-cmake, v0.1.4
language-docker, v1.1.6
language-gmsh, v0.1.0
language-latex, v0.6.1
language-moose, v0.17.0
language-qml, v1.0.0
linter, v1.11.4
linter-chktex, v1.3.0
linter-gcc, v0.6.14
linter-moose, v0.4.0
linter-python-pep8, v0.2.0
markdown-writer, v2.3.3
merge-conflicts, v1.4.2
terminal-plus, v0.14.5
wordcount, v2.6.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by muayyad-alsadi**
https://github.com/atom/autocomplete-plus/issues/722

### CODE REVIEW

**Comment by 50Wliu** [comment]
@muayyad-alsadi Can you please add a spec for this?  Thanks!

**Comment by muayyad-alsadi** [comment]
@50Wliu  I'm not very familiar with your code structure

the affected function `isCurrentFileBlackListed` is called by `findSuggestions` which already have a spec in a file called `spec/autocomplete-manager-integration-spec.coffee` near line `1723` and `1742`



https://github.com/atom/autocomplete-plus/blob/master/spec/autocomplete-manager-integration-spec.coffee#L1723

the problem with current specs that they open an existing file `atom.workspace.open('sample.js')` and the bug is cased by a new unsaved file (without path). which is supposed to already be tested by `atom.workspace.open('')` but I'm not sure why it did not trigger the error.

**Comment by the-question** [comment]
Just some thoughts:
Wouldn't it be better to consider the file as blacklisted (`return true`) if it's not saved.
It's difficult to know when a file is still empty (or nearly empty) what kind of content it will have and if the user will want to have autocomplete enabled on it. Moreover if the user kept the file as `Plain Text`, it may be hard to know how to autocomplete user's input.

Like @muayyad-alsadi, I'm not familiar with this plugin code, so I'm not sure that my comment makes any real sense.

My 2¢

**Comment by lee-dohm** [comment]
This is unnecessary when running Atom with a supported version of Electron. It is true that we'll have to address this eventually, but I think we'll address it in a more comprehensive way.

**Comment by muayyad-alsadi** [comment]
> Atom with a supported version of Electron

what version is the supported version of Electron?

**Comment by 50Wliu** [comment]
The version defined [here](https://github.com/atom/atom/blob/master/package.json#L15) (though note that's for `master` and not any released versions - you'll need to check the individual release branches for those).

It's currently 0.37.8 for Atom 1.9.0 and up and 0.36.8 for Atom 1.8.0.

**Comment by muayyad-alsadi** [comment]
so atom does not support 1.x release of electron?
please confirm this.

**Comment by the-question** [comment]
As I understand it, Atom isn't officially compatible with Electron 1.x, and as we can see, it's actually not fully compatible with it. But, as far as I can tell, it already works pretty well!
Maybe someone should [open a new issue in Atom repository](https://github.com/atom/atom/issues/new) for that purpose _(Electron 1.x compatibility)_.

**Comment by 50Wliu** [comment]
> so atom does not support 1.x release of electron?

As of this writing Atom does not support using anything other than the versions defined in its `package.json`.  So no, Atom does not support using Electron 1.x.

**Comment by muayyad-alsadi** [comment]
understood.

@50Wliu  is there any published reason for choosing an old legacy version of Electron? any link to any public discussion, ticket/issue, mailing list, ...etc. 

was picking this specific old random version an aware decision or it just happened like that?

**Comment by muayyad-alsadi** [comment]
I opened an issue and here is the link

https://github.com/atom/atom/issues/11967

**Comment by 50Wliu** [comment]
0.37.8 is the last pre-1.0 version of Electron.  We're not upgrading to 1.x yet as we need to give package authors some time to update and move away from deprecated APIs.

**Comment by muayyad-alsadi** [comment]
are we even sure it's about the version of Electron?

**Comment by 50Wliu** [comment]
@muayyad-alsadi Can you clarify?

**Comment by muayyad-alsadi** [comment]
bug #722 is closed because it's reported on "unsupported version of Electron"
the trace seems to be a missing silly "if" statement before calling get basename of a file that can be undefined. I'm not sure how this can be a result of Electron's version.

I was told Electron new version removed deprecated APIs. I can't see a link between this #722 and Electron version. It was just a guess.

**Comment by 50Wliu** [comment]
> I'm not sure how this can be a result of Electron's version.

Newer versions of Electron also use newer versions of Node (specifically I believe v6 or so?).  `path` is a Node API that added stricter checking to its passed-in arguments, leading to the error in #722.

**Pull request closed without merging**
