### PR TITLE
"Typing confirms selection" option (YouCompleteMe style)

### PR DESCRIPTION
**Pull request by evindor**
Short screencast: https://www.youtube.com/watch?v=R7Tg6WzDiNM&feature=youtu.be&html5=1

This patch adds an option to make autocomplete-plus behave like vim/YouCompleteMe. You won't have anything selected from the start, but if you select anything from the list you can just continue typing to confirm your selection. Though in vim you get your selection inserted into the document but it doesn't really matter as long as this patch provides the same workflow (nothing selected by default + just continue typing to confirm).

### CODE REVIEW

**Comment by evindor** [comment]
I think it's close enough to what was requested in #240

**Comment by joefitzgerald** [comment]
This kind of breaks one of the core tenants of autocomplete-plus - that is; if you keep typing, the suggestion list will refine suggestions as you type and you can typically get to the point where the suggestion you want is automatically selected; and confirm it with a single keystroke.

Switching to this model requires explicit selection to get any confirmation, and consequently :-1: on this. It's an interesting concept, for sure.

**Comment by Rasarts** [comment]
cool, whant this!

**Comment by rumpelsepp** [comment]
Yeah; like deoplete! I want this!

**Comment by damieng** [comment]
Long since out of date and unmerged.

**Pull request closed without merging**
