### PR TITLE
Scroll to selected items one by one when going up

### PR DESCRIPTION
**Pull request by MayhemYDG**
It really bothers me that the behaviors differ between scrolling down and scrolling up.

### CODE REVIEW

**Comment by joefitzgerald** [comment]
@mayhemydg would it be possible to post a picture / pictures to illustrate how this changes the behavior?

**Comment by MayhemYDG** [comment]
Before:
before

After:
after

**Comment by joefitzgerald** [comment]
LGTM. @benogle?

**Comment by benogle** [comment]
Seems fine

**Pull request merged**
