### PR TITLE
Fix an escape bug in snippets

### LINKED ISSUE #773: \ in snippets not displayed correctly in ac list
When using the `snippet` attribute on an autocomplete suggestion, it treats `\` as the escape character. To show the `\` character in the suggestions, we have to escape it as `\\`.

The bug in autocomplete-plus about this is that it shows `\\` in suggestion list, and inserts `\`. It was worked around in one of my packages in https://github.com/steelbrain/autocomplete-hack/pull/22/commits/1a71c16df543b524d763d727d3c1f970861ffa26.

The expected behavior for it would be to show `\` in both the list and inserted text.

To repro this bug set `snippet: 'Some \\ Where \\ Sunny'` on an autocomplete suggestion, then observe the visible text and mutation to the editor text after you select it.
Would you be willing to review a PR fixing this? I have a locally working fix that I would love to upstream.

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #773

### CODE REVIEW

**Comment by 50Wliu** [comment]
Look good to me.

/cc @atom/feedback

**Comment by as-cii** [comment]
Hey @steelbrain, thanks for submitting this pull request! It definitely seems like what we show in the suggestion list doesn't match what ends up being inserted in the buffer, so great catch there! ✨

It's not entirely clear to me why having `"\\\\"` shouldn't display two backslashes (`\\`), as it would seem like that's the intent of the snippet author. Could you clarify why we should show and insert just one instead?

**Comment by steelbrain** [comment]
Hi @as-cii. This PR does not modify the behavior of the snippets when they are executed in the editor, it just changes how they are shown in list. In javascript, to type `\` we have to write it as `\\`, and because `\` is an escape character in snippets, we have to write it as `\\\\`.

What was happening before is that the list was displaying `\\` (in js value) as is. Whereas when we execute the snippet, we get `\` (in js value). This PR corrects the list behavior so we have a consistent behavior in both parts.

**Comment by as-cii** [comment]
That makes sense! Thanks for this, @steelbrain! 🎉

**Pull request merged**
